@baseUrl = http://127.0.0.1:8000

###############################################################################
# Welcome - Quick health check to verify the service is running
###############################################################################

### Welcome Message
GET {{baseUrl}}
Content-Type: application/json
