"""Embedding Playground page - 3D visualization and similarity comparison."""

from typing import Any

import numpy as np
import plotly.graph_objects as go
import streamlit as st
from frontend.utils import api
from frontend.utils.layout import setup_page
from frontend.utils.theme import ACCENT_GREEN, ACCENT_ORANGE, ACCENT_RED, IST_BLUE
from sklearn.decomposition import PCA

setup_page("Embedding Playground")

# Colors for up to 8 texts in the 3D plot
POINT_COLORS = [
    IST_BLUE,
    ACCENT_GREEN,
    ACCENT_ORANGE,
    ACCENT_RED,
    "#8b5cf6",  # purple
    "#ec4899",  # pink
    "#06b6d4",  # cyan
    "#84cc16",  # lime
]

_DOT_EMOJIS = "🔵🟢🟡🔴🟣🩷🩵🟩"


def _similarity_color(sim: float) -> str:
    """Return a color based on similarity value."""
    if sim >= 0.8:
        return ACCENT_GREEN
    if sim >= 0.5:
        return ACCENT_ORANGE
    return ACCENT_RED


def _similarity_label(sim: float) -> str:
    """Return a short label describing how similar two texts are."""
    if sim >= 0.9:
        return "Very high similarity"
    if sim >= 0.8:
        return "High similarity"
    if sim >= 0.6:
        return "Moderate similarity"
    if sim >= 0.4:
        return "Low similarity"
    return "Very low similarity"


# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
st.markdown("<h1>🚀 Embedding Playground</h1>", unsafe_allow_html=True)
st.caption("Type sentences, turn them into 3072-dimensional vectors, and watch meaning come alive in 3D.")

# ---------------------------------------------------------------------------
# Explanation
# ---------------------------------------------------------------------------
with st.expander("💡 What are embeddings?", expanded=False):
    st.markdown(
        """
        **Embeddings** are high-dimensional vectors (in our case, **3072 dimensions!**)
        that capture the *meaning* of text. They're generated by a neural network
        (Azure OpenAI `text-embedding-3-large`).

        **Think of it like this:**
        - Each sentence gets a unique "address" in a 3072-dimensional space
        - Sentences about similar topics live in the same "neighborhood"
        - We measure closeness using **cosine similarity** (1.0 = same meaning, 0.0 = unrelated)
        - To visualize this, we use **PCA** to squash 3072D down to 3D

        **Pro tip:** Try mixing similar and completely unrelated sentences to see the effect!
        """
    )

st.divider()

# ---------------------------------------------------------------------------
# Input area
# ---------------------------------------------------------------------------
st.subheader("✏️ Input Sentences")
st.caption("Add 2-8 sentences. Give each a short label for the graph, then write the full text.")

# Default entries: (label, text)
_DEFAULTS = [
    (
        "SINFO conference",
        "SINFO is the largest student-run tech conference in Portugal,"
        " held annually at Instituto Superior Tecnico in Lisbon.",
    ),
    (
        "IST tech week",
        "Every year, thousands of engineering students gather in Lisbon"
        " for a week of tech talks, workshops, and networking at IST.",
    ),
    (
        "RAG overview",
        "Retrieval-Augmented Generation combines a vector search over"
        " document embeddings with a large language model to answer"
        " questions using real sources.",
    ),
    (
        "RAG pipeline",
        "RAG pipelines first retrieve relevant text chunks from a"
        " database and then feed them as context to an LLM for"
        " grounded answers.",
    ),
    (
        "Pasta recipe",
        "The best recipe for homemade pasta starts with 100 grams of"
        " flour per egg, kneaded for ten minutes until the dough is"
        " smooth and elastic.",
    ),
]

if "embed_entries" not in st.session_state:
    st.session_state["embed_entries"] = list(_DEFAULTS)

entries = st.session_state["embed_entries"]

# Render inputs — each entry is a visual card: colored header row + text area
updated_entries: list[tuple[str, str]] = []
for i in range(len(entries)):
    dot = _DOT_EMOJIS[i] if i < len(_DOT_EMOJIS) else "⚪"
    color = POINT_COLORS[i % len(POINT_COLORS)]

    with st.container(border=True):
        # Header row: dot + label + remove
        header_left, header_right = st.columns([9, 1])
        with header_left:
            lbl = st.text_input(
                f"Label {i + 1}",
                value=entries[i][0],
                key=f"embed_label_{i}",
                label_visibility="collapsed",
                placeholder=f"Label for sentence {i + 1}",
            )
        with header_right:
            if len(entries) > 2 and st.button("✕", key=f"remove_{i}", help="Remove this entry"):
                st.session_state["embed_entries"] = [e for j, e in enumerate(entries) if j != i]
                st.rerun()

        # Full-width text area
        txt = st.text_area(
            f"Sentence {i + 1}",
            value=entries[i][1],
            key=f"embed_text_{i}",
            label_visibility="collapsed",
            placeholder="Full sentence to embed...",
            height=80,
        )

    updated_entries.append((lbl.strip(), txt.strip()))

st.session_state["embed_entries"] = updated_entries

btn_col1, btn_col2 = st.columns([1, 1])
with btn_col1:
    if len(entries) < 8 and st.button("➕  Add sentence", use_container_width=True):
        st.session_state["embed_entries"].append(("", ""))
        st.rerun()
with btn_col2:
    compare_clicked = st.button("🚀  Compare Embeddings", use_container_width=True, type="primary")

st.divider()

# ---------------------------------------------------------------------------
# Results
# ---------------------------------------------------------------------------
if compare_clicked:
    # Filter out entries with empty text
    valid_entries = [(lbl or f"Sentence {i + 1}", txt) for i, (lbl, txt) in enumerate(updated_entries) if txt]

    if len(valid_entries) < 2:
        st.warning("Enter at least 2 non-empty sentences to compare.")
        st.stop()

    _labels = [lbl for lbl, _ in valid_entries]
    _texts = [txt for _, txt in valid_entries]

    with st.spinner("Turning words into vectors... 🔢"):
        try:
            _api_result = api.compare_embeddings(_texts)
        except Exception as exc:
            st.error(f"API call failed: {exc}")
            st.stop()

    st.session_state["embed_result"] = _api_result
    st.session_state["embed_valid_texts"] = _texts
    st.session_state["embed_valid_labels"] = _labels

# Show results from session state (persists across reruns)
result: dict[str, Any] | None = st.session_state.get("embed_result")
valid_texts: list[str] | None = st.session_state.get("embed_valid_texts")
valid_labels: list[str] | None = st.session_state.get("embed_valid_labels")

if result is None or valid_texts is None:
    st.markdown(
        """
        <div class="cta-placeholder">
            <p style="font-size: 1.3em;">👆 Enter some sentences and hit
            <b style="color: #009de0;">Compare Embeddings</b></p>
            <p style="font-size: 0.9em;">The magic happens when you mix related and unrelated sentences!</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.stop()

embeddings_data = result.get("embeddings", [])
similarities = result.get("similarities", [])

# Build a text -> label lookup (the API returns full texts, we want to show labels)
text_to_label: dict[str, str] = {}
if valid_labels:
    for txt, lbl in zip(valid_texts, valid_labels, strict=True):
        text_to_label[txt] = lbl
# Fallback: use truncated text as label
for e in embeddings_data:
    if e["text"] not in text_to_label:
        text_to_label[e["text"]] = e["text"][:30] + "..."

# ---------------------------------------------------------------------------
# 3D Visualization
# ---------------------------------------------------------------------------
st.subheader("🌌 3D Embedding Space")
st.caption("3072 dimensions → 3D via PCA. Points that are close together share similar meaning.")

# Extract embedding vectors
vectors = [e["embedding"] for e in embeddings_data]
full_texts = [e["text"] for e in embeddings_data]
point_labels = [text_to_label.get(t, t[:30]) for t in full_texts]

if len(vectors) < 2:
    st.warning("Need at least 2 embeddings to visualize.")
    st.stop()

# PCA reduction to 3D
# N centered points span at most N-1 dimensions, so we can only extract
# min(3, N-1) meaningful principal components.  For any missing dimensions
# we add a small amount of jitter so the points still look like they live in
# 3D space rather than collapsing to a line or plane.
matrix = np.array(vectors)
meaningful_dims = min(3, max(len(vectors) - 1, 1))
pca = PCA(n_components=meaningful_dims)
coords = pca.fit_transform(matrix)

if coords.shape[1] < 3:
    spread = np.ptp(coords, axis=0).mean() if coords.size else 1.0
    jitter_scale = spread * 0.3
    rng = np.random.default_rng(42)
    jitter = rng.normal(scale=jitter_scale, size=(coords.shape[0], 3 - coords.shape[1]))
    coords = np.concatenate([coords, jitter], axis=1)

# Build 3D scatter plot
fig = go.Figure()

for i, (plabel, coord, full_text) in enumerate(zip(point_labels, coords, full_texts, strict=True)):
    color = POINT_COLORS[i % len(POINT_COLORS)]

    fig.add_trace(
        go.Scatter3d(
            x=[coord[0]],
            y=[coord[1]],
            z=[coord[2]],
            mode="markers+text",
            marker=dict(size=12, color=color, opacity=0.9),
            text=[plabel],
            textposition="top center",
            textfont=dict(size=12, color=color),
            name=plabel,
            hovertext=full_text,
            hoverinfo="text",
        )
    )

# Draw lines between each pair colored by similarity
for pair in similarities:
    text_a = pair["text_a"]
    text_b = pair["text_b"]
    sim = pair["similarity"]

    idx_a = full_texts.index(text_a)
    idx_b = full_texts.index(text_b)
    label_a = text_to_label.get(text_a, "")
    label_b = text_to_label.get(text_b, "")

    line_color = _similarity_color(sim)
    opacity = 0.2 + 0.6 * sim

    fig.add_trace(
        go.Scatter3d(
            x=[coords[idx_a][0], coords[idx_b][0]],
            y=[coords[idx_a][1], coords[idx_b][1]],
            z=[coords[idx_a][2], coords[idx_b][2]],
            mode="lines",
            line=dict(color=line_color, width=3),
            opacity=opacity,
            name=f"{label_a} ↔ {label_b}: {sim:.3f}",
            hovertext=f"{label_a} ↔ {label_b}: {sim:.4f}",
            hoverinfo="text",
            showlegend=False,
        )
    )

fig.update_layout(
    scene=dict(
        xaxis=dict(title="PC1"),
        yaxis=dict(title="PC2"),
        zaxis=dict(title="PC3"),
    ),
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    margin=dict(l=0, r=0, t=30, b=0),
    height=600,
    legend=dict(font=dict(size=11)),
)

st.plotly_chart(fig, width="stretch")

# Explained variance info
explained = pca.explained_variance_ratio_
total_explained = sum(explained) * 100
pca_parts = [f"PC{i + 1}: {v * 100:.1f}%" for i, v in enumerate(explained)]
pca_detail = ", ".join(pca_parts)
jitter_note = ""
if meaningful_dims < 3:
    missing = 3 - meaningful_dims
    pc_label = "PC3 is" if missing == 1 else "PC2 & PC3 are"
    jitter_note = f"  |  {pc_label} synthetic jitter (not enough points for full 3D PCA)"
st.caption(f"PCA explained variance: {total_explained:.1f}% ({pca_detail}){jitter_note}")

st.divider()

# ---------------------------------------------------------------------------
# Similarity scores
# ---------------------------------------------------------------------------
st.subheader("📏 Similarity Score")
st.caption(
    "Cosine similarity between each pair of sentences. "
    "Ranges from 0 (completely unrelated) to 1 (identical meaning). "
    "Higher score = more similar."
)

for pair in similarities:
    sim = pair["similarity"]
    color = _similarity_color(sim)
    label_a = text_to_label.get(pair["text_a"], pair["text_a"][:40])
    label_b = text_to_label.get(pair["text_b"], pair["text_b"][:40])
    sim_label = _similarity_label(sim)
    pct = max(0, min(100, sim * 100))

    st.markdown(
        f"""
        <div class="sim-card">
            <div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 8px;">
                <div style="flex: 1; min-width: 200px;">
                    <b>{label_a}</b>
                    <span class="text-muted"> vs. </span>
                    <b>{label_b}</b>
                </div>
                <div style="text-align: right; min-width: 120px;">
                    <span style="color: {color}; font-weight: bold; font-size: 1.5em;">{sim:.4f}</span><br/>
                    <span style="color: {color}; font-size: 0.8em;">{sim_label}</span>
                </div>
            </div>
            <div class="sim-bar" style="margin-top: 10px;">
                <div class="sim-bar-fill" style="width: {pct}%; background-color: {color};"></div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

st.divider()

# ---------------------------------------------------------------------------
# Embedding details
# ---------------------------------------------------------------------------
st.subheader("🔬 Embedding Details")
st.caption("Dive into the raw numbers behind each sentence's vector.")

for i, emb in enumerate(embeddings_data):
    dot = _DOT_EMOJIS[i] if i < len(_DOT_EMOJIS) else "⚪"
    plabel = text_to_label.get(emb["text"], f"Sentence {i + 1}")
    with st.expander(f"{dot}  {plabel}"):
        st.markdown(f"**Full text:** {emb['text']}")
        st.markdown(f"**Dimensions:** `{emb['dimensions']}`")

        vec = emb["embedding"]
        st.markdown("**First 20 values** (out of 3072):")
        st.code(
            ", ".join(f"{v:.6f}" for v in vec[:20]) + f"  ... ({len(vec)} total)",
            language=None,
        )

        st.markdown("**Vector statistics:**")
        arr = np.array(vec)
        stat_cols = st.columns(4)
        stat_cols[0].metric("Min", f"{arr.min():.6f}")
        stat_cols[1].metric("Max", f"{arr.max():.6f}")
        stat_cols[2].metric("Mean", f"{arr.mean():.6f}")
        stat_cols[3].metric("Std Dev", f"{arr.std():.6f}")
